### ISSUE TITLE
Can't compile.

### ISSUE THREAD

**Issue by theunixer** [ZigEmbeddedGroup/raspberrypi-rp2040#64]
I have done this:
`
git clone https://github.com/ZigEmbeddedGroup/raspberrypi-rp2040.git
cd raspberrypi-rp2040/
`

Tried to build using this command:
`
zig build
`

Got this:
`
/home/alex/Documents/raspberrypi-rp2040/build.zig:7:30: error: unable to load '/home/alex/Documents/raspberrypi-rp2040/deps/microzig/build.zig': FileNotFound
pub const microzig = @import("deps/microzig/build.zig");
                             ^~~~~~~~~~~~~~~~~~~~~~~~~
`

Fixed this with:
`
gut clone https://github.com/ZigEmbeddedGroup/microzig.git
mv microzig/ deps/
`

After I try to build it again, I see this:
`
zig build-exe random Debug thumb-freestanding-none: error: the following command failed with 1 compilation errors:
/snap/zig/7686/zig build-exe /home/alex/Documents/raspberrypi-rp2040/deps/microzig/src/start.zig -fno-strip --cache-dir /home/alex/Documents/raspberrypi-rp2040/zig-cache --global-cache-dir /home/alex/.cache/zig --name random -fcompiler-rt -fsingle-threaded -target thumb-freestanding-none -mcpu cortex_m0plus --script /home/alex/Documents/raspberrypi-rp2040/rp2040.ld --mod config::/home/alex/Documents/raspberrypi-rp2040/zig-cache/microzig/config-969498c921793a9e671f14070bafbe74.zig --mod app:microzig:/home/alex/Documents/raspberrypi-rp2040/examples/random.zig --mod hal:microzig:/home/alex/Documents/raspberrypi-rp2040/src/hal.zig --mod cpu:microzig:/home/alex/Documents/raspberrypi-rp2040/deps/microzig/src/modules/cpus/cortex-m.zig --mod chip:microzig:/home/alex/Documents/raspberrypi-rp2040/src/chips/RP2040.zig --mod microzig:config,chip,cpu,hal,board:/home/alex/Documents/raspberrypi-rp2040/deps/microzig/src/microzig.zig --mod board:microzig:/home/alex/Documents/raspberrypi-rp2040/src/boards/raspberry_pi_pico.zig --deps app,microzig --listen=- 
Build Summary: 24/27 steps succeeded; 1 failed (disable with --summary none)
install transitive failure
└─ install random transitive failure
   └─ zig build-exe random Debug thumb-freestanding-none 1 errors
/snap/zig/7686/lib/std/math.zig:437:17: error: deprecated; use @min instead
pub const min = @compileError("deprecated; use @min instead");
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
    min: /snap/zig/7686/lib/std/rand/Ascon.zig:12:21
    fill: /snap/zig/7686/lib/std/rand/Ascon.zig:53:19
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
`

OS - `Kubuntu 22.04.2 LTS x86_64`

**Comment by mattnite** [comment]
There are git submodules, run:

```
git submodule update --init --recursive
```

**Comment by theunixer** [comment]
Thank you for your response.
After cloning  repo again and running 
`
git submodule update --init --recursive
`
I still get 
`
zig build-exe random Debug thumb-freestanding-none: error: the following command failed with 1 compilation errors:
/snap/zig/7734/zig build-exe /home/alex/raspberrypi-rp2040/deps/microzig/src/start.zig -fno-strip --cache-dir /home/alex/raspberrypi-rp2040/zig-cache --global-cache-dir /home/alex/.cache/zig --name random -fcompiler-rt -fsingle-threaded -target thumb-freestanding-none -mcpu cortex_m0plus --script /home/alex/raspberrypi-rp2040/rp2040.ld --mod board:microzig:/home/alex/raspberrypi-rp2040/src/boards/raspberry_pi_pico.zig --mod hal:microzig:/home/alex/raspberrypi-rp2040/src/hal.zig --mod chip:microzig:/home/alex/raspberrypi-rp2040/src/chips/RP2040.zig --mod config::/home/alex/raspberrypi-rp2040/zig-cache/microzig/config-a7f1609d0013964d3f3a48cf7eef1cea.zig --mod cpu:microzig:/home/alex/raspberrypi-rp2040/deps/microzig/src/modules/cpus/cortex-m.zig --mod app:microzig:/home/alex/raspberrypi-rp2040/examples/random.zig --mod microzig:config,chip,cpu,hal,board:/home/alex/raspberrypi-rp2040/deps/microzig/src/microzig.zig --deps app,microzig --listen=- 
Build Summary: 24/27 steps succeeded; 1 failed (disable with --summary none)
install transitive failure
└─ install random transitive failure
   └─ zig build-exe random Debug thumb-freestanding-none 1 errors
/snap/zig/7734/lib/std/math.zig:437:17: error: deprecated; use @min instead
pub const min = @compileError("deprecated; use @min instead");
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
    min: /snap/zig/7734/lib/std/rand/Ascon.zig:12:21
    fill: /snap/zig/7734/lib/std/rand/Ascon.zig:53:19
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
`

My zig version - `0.11.0-dev.3731+c6e2e1ae4`

**Comment by theunixer** [comment]
Deprecated function is used in this file:  `/snap/zig/7734/lib/std/rand/Ascon.zig`. I can not change it, it is read-only file.

**Comment by theunixer** [comment]
I have reinstalled zig(0.11.0-dev.3747+7b5bd3a93). Now when I try to build I get another error:
`
deps/microzig/src/start.zig:144:25: error: invalid builtin function: '@ptrToInt'
        const bss_len = @ptrToInt(bss_end) - @ptrToInt(bss_start);
`

**Comment by mattnite** [comment]
Looks like recent breaks on zig master, I will fix these asap. Btw the next stable release should be coming out in the next few weeks. Once that happens we're sticking to stable releases from then on out so that this doesn't happen to users.

**Comment by theunixer** [comment]
Okay, thank you for your work.
