### ISSUE TITLE
Clear instructions on how to get Console over USB

### ISSUE THREAD

**Issue by thuvasooriya** [ZigEmbeddedGroup/raspberrypi-rp2040#81]
Hi I'm a beginner in all these. I was looking for a way to enable console over USB rather than UART. I repeatedly failed. If someone can point me in the right direction it would be awesome. I'm looking forward to making this code work in waveshare rp2040 zero and rp2040 lcd.96 and contributing to the community. Please help me get started. Sorry if this is not the place for these type of questions.

**Comment by ikskuh** [comment]
The tl;dr:
To get console on USB instead of UART, you just have to implement the USB CDC class :tongue: 

We don't have those parts implemented yet, we only have USB HID available as a device protocol, but not others.

**Comment by thuvasooriya** [comment]
> The tl;dr: To get console on USB instead of UART, you just have to implement the USB CDC class 👅
> 
> We don't have those parts implemented yet, we only have USB HID available as a device protocol, but not others.

Thank you for the clarification. I wasn't sure whether it was implemented or not and tried a bunch of hid examples relentlessly. Sorry for the trouble. Any tips on getting started with implementing those classes would be helpful. I'm currently learning zig and would like to contribute. Thanks anyway.

**Comment by ikskuh** [comment]
cc @r4gus: can you give some pointers on how to get started?

**Comment by r4gus** [comment]
Sure, so I the first step would be to 

1. check if you can get the [USB HID](https://github.com/ZigEmbeddedGroup/raspberrypi-rp2040/blob/main/examples/usb_hid.zig) example running. There is a corresponding [test script](https://github.com/ZigEmbeddedGroup/raspberrypi-rp2040/blob/main/examples/scripts/hid_test.py) you can use to transfer messages. 
2. The next step would be to get a basic understanding of how the usb code is structured. You have to cross reference [Micorzig](https://github.com/ZigEmbeddedGroup/microzig/blob/main/src/core/usb.zig) and the [rp2040 repo](https://github.com/ZigEmbeddedGroup/raspberrypi-rp2040/blob/main/src/hal/usb.zig). As we split things up it might take some time to understand it (you cant really read it top to bottom).
3. Look at the [TinyUSB repo](https://github.com/hathach/tinyusb/tree/46f7cf4da2959b96d3af6b7f23d0d02ff7187f2f/src/class/cdc) and port the CDC code. I wouldn't reinvent the wheel, just look how they did it.

I have never looked at CDC so I cant give you any specific advice but in general make small incremental steps and get something on the screen you can verify. Dont port the whole thing at once.

You might have to adapt the Microzig USB code. Best approach here is to copy it over to your rp2040 branch so you dont have to work at two repos at once.
